name: bitorzo_wallet_flutter
description: Bitorzo - Fast, Robust & Secure BTC Wallet.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 3.0.0+88

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_auth: ^0.16.1

  provider: ^4.0.5+1

  bip39: ^1.0.3

  random_string: ^2.1.0

  bitcoin_flutter: ^2.0.1
  # Permission handler for contacts
  permission_handler: ^5.0.0+hotfix.8

  # DB communication
  cloud_firestore: ^0.13.6

  # retrieve user contacts
  contacts_service: ^0.4.6


  # Securley store data in a keystore
  flutter_secure_storage: ^3.3.3
  charts_flutter: ^0.9.0

  # BTC core functions
  flutter_nano_ffi: ^1.0.2

  # Shared prefs
  shared_preferences: ^0.5.7

  # Flare for animations
  flare_flutter: ^2.0.3

  # Websockets
  web_socket_channel: ^1.1.0

  # Platform-specific build info
  package_info: ^0.4.0+17

  # Device-specific info
  device_info: ^0.4.2+2

  # JSON Serialization
  json_annotation: ^3.0.1

  # Localization
  intl: ^0.16.0

  # BigDecimal alternative
  decimal: ^0.3.5

  # Logger
  logger: ^0.9.1

  # Native webview plugin
  flutter_webview_plugin: ^0.3.11

  # SQLite
  sqflite: ^1.3.0

  # Android/iOS path provider
  path_provider: ^1.6.7


  # TouchID/FaceID
  local_auth: ^0.6.2+1

  # Eventbus
  event_taxi: ^0.1.5

  # SVG
  flutter_svg: ^0.18.0
    
  # QR Codes
  qr_flutter: ^2.0.1 # Generator
  barcode_scan:
    git:
      url: https://github.com/bbedward/flutter_barcode_reader.git
      ref: master

  # Share files
  share:
    git:
      url: https://github.com/bbedward/plugins.git
      path: packages/share
      ref: master

  # File picker
  file_picker: ^1.8.0+2

  # Deep link support
  #uni_links: ^0.2.0
  uni_links:
    git:
      url: https://github.com/CathalT/uni_links.git
      ref: nfc_android

  # HTTP client
  http: ^0.12.1

  # Vibrate
  vibrate:
    git:
      url: https://github.com/bbedward/flutter_vibrate.git
      ref: master

  # Toast
  oktoast: ^2.3.2

  # Push notifications
  firebase_messaging: ^6.0.13

  # Slidable list actions
  flutter_slidable: ^0.5.4

  # Lock helper
  synchronized: ^2.2.0

  # Service provider
  get_it: ^4.0.2

  # Root/Jailbreak detection
  root_checker:
    git:
      url: https://github.com/bbedward/root_checker.git
      ref: master

  # Validation utilities
  validators: ^2.0.0+1

  # Auto resize text widget
  auto_size_text: ^2.1.0

  # Avoid keyboard from overlapping text fields
  keyboard_avoider: ^0.1.2

  # Manta dart implementation
  manta_dart:
    git:
      url: https://github.com/bbedward/manta-dart.git
      ref: master

dev_dependencies:

  #flutter_test:
    #sdk: flutter
 # flutter_launcher_icons: ^0.7.3
  build_runner: ^1.7.0
  json_serializable: ^3.2.5
  intl_translation: ^0.17.9

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: NunitoSans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 600
        - asset: fonts/NunitoSans-ExtraLight.ttf
          weight: 100
        - asset: fonts/NunitoSans-Light.ttf
          weight: 200
        - asset: fonts/NunitoSans-SemiBold.ttf
          weight: 700
        - asset: fonts/NunitoSans-Bold.ttf
          weight: 800

        - asset: fonts/NunitoSans-ExtraBold.ttf
          weight: 900
    - family: OverpassMono
      fonts:
        - asset: fonts/OverpassMono-Regular.ttf
          weight: 600
        - asset: fonts/OverpassMono-Light.ttf
          weight: 100
    - family: AppIcons
      fonts:
        - asset: fonts/AppIcons.ttf
          weight: 500
    - family: Comfortaa
      fonts:
        - asset: fonts/Comfortaa-Bold.ttf
          weight: 700
        - asset: fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: fonts/Comfortaa-Light.ttf
          weight: 300
  assets:
    - assets/QR.svg
    - assets/welcome_animation.flr
    - assets/send_animation.flr
    - assets/manta_animation.flr
    - assets/transfer_animation_natriumwalletonly.flr
    - assets/transfer_animation_paperwalletonly.flr
    - assets/searchseedqr_animation_magnifyingglassonly.flr
    - assets/searchseedqr_animation_glassonly.flr
    - assets/searchseedqr_animation_qronly.flr
    - assets/searchseedmanual_animation_magnifyingglassonly.flr
    - assets/searchseedmanual_animation_glassonly.flr
    - assets/searchseedmanual_animation_seedonly.flr
    - assets/threedot_animation.flr
    - assets/offline_animation.flr
    - assets/sharecard_logo.svg
    - assets/transferfunds_illustration_start_natriumwalletonly.svg
    - assets/transferfunds_illustration_start_paperwalletonly.svg
    - assets/transferfunds_illustration_end_natriumwalletonly.svg
    - assets/transferfunds_illustration_end_paperwalletonly.svg
    - assets/pulltosend_animation.flr
    - assets/sheethandle_animation.flr
    - android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
    - assets/images/
    - data/
    
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
